server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
          #feign日志级别
          # NONE：默认的，不显示任何日志;
          # BASIC：仅记录请求方法、URL、响应状态码及执行时间;
          # HEADERS：除了BASIC中定义的信息之外，还有请求和响应的头信息;
        # FULL：除了HEADERS中定义的信息之外，还有请求和响应的正文及元数据。
        loggerLevel: full
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.zhixi.*: debug
