server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zhixi158
#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  type-aliases-package: com.zhixi.pojo
  configuration:
    map-underscore-to-camel-case: true
#日志
logging:
  level:
    com.zhixi: debug

