server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.195.160:8848 #Nacos服务注册中心地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
