server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # 配置微服务链路追踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 # 配置采样率，默认的采样比例为：0:1，即10%，所设置的值介于0-1之间，1则表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zhixi158
#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  type-aliases-package: com.zhixi.pojo
  configuration:
    map-underscore-to-camel-case: true
#日志
logging:
  level:
    com.zhixi: debug

# Eureka客户端配置
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  # 服务端的服务发现页面和健康检查地址
  instance:
    instance-id: payment8001
    # 显示IP地址
    prefer-ip-address: true