server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://gitee.com/zhang-zhixi/spring-cloud-config.git
          # 配置仓库中的哪个目录下的配置文件被读取
          search-paths:
            - SpringCloud-Config
          # 配置Gitee的用户名和密码
          username: 1820712542@qq.com
          password: zhixi158
      ####读取分支
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: 182.92.209.212
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka

# rabbitmq相关配置,暴露bus刷新配置的端点
# curl http://localhost:3344/actuator：暴露bus刷新配置的端点
# curl -X POST http://localhost:3344/actuator/bus-refresh：刷新配置
# curl -X POST http://localhost:3344/actuator/bus-refresh/config-client:3355：刷新3355端口的配置
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"
# 日志
logging:
  level:
    com.zhixi.*: debug