server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
# Eureka客户端配置
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  # 服务端的服务发现页面和健康检查地址
  instance:
    instance-id: provider-hystrix-payment-8001
    # 显示IP地址
    prefer-ip-address: true