server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.195.160:8848
        username: nacos
        password: nacos
        namespace: 500b6131-1f25-4fb5-a8cb-483f2ab8b76d
        group: SEATA_GROUP
  # 订单数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.209.212:3306/seata_order
    username: root
    password: zhixi158

seata:
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group  #对应seataServer.properties中的service.vgroupMapping.my_test_tx_group 集群分组
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      server-addr: 43.143.195.160:8848
      group: SEATA_GROUP
      namespace: 500b6131-1f25-4fb5-a8cb-483f2ab8b76d # seata-server的配置文件的命名空间ID
      dataId: seataServer.properties       # seata-server在nacos的配置dataId
      username: nacos
      password: nacos
  registry:
    type: nacos   #注册中心类型：nacos
    nacos:
      server-addr: 43.143.195.160:8848    # nacos的地址端口
      group : SEATA_GROUP            # seata-server在nacos的分组
      namespace: 500b6131-1f25-4fb5-a8cb-483f2ab8b76d           # seata-server在nacos的命名空间ID
      username: nacos                # nacos账号
      password: nacos                # nacos密码

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath*:mapper/*.xml



