server:
  port: 8802
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #配置要绑定的rabbitmq的服务信息
        rabbit: #表示定义的名称，用于bingding的整合
          type: rabbit
          # 设置rabbitmq的连接信息
          environment:
            rabbitmq:
              host: 182.92.209.212
              port: 5672
              username: guest
              password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: rabbit # 表示要绑定的rabbitmq的服务信息
          group: studyExchangeGroup # 设置消费者的组名，如果不设置，那么就是广播模式
  #rabbitmq相关配置
  rabbitmq:
    host: 182.92.209.212
    port: 5672
    username: guest
    password: guest
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    prefer-ip-address: true     # 访问的路径变为IP地址
