server:
  port: 80
spring:
  application:
    name: cloud-consumer-order

# 订单服务调用支付服务
order:
  payment:
    service:
      # 服务名
      url: http://cloud-payment-service

# Eureka客户端配置
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka